### ISSUE TITLE
Does this work on a Jetson Nano?

### ISSUE THREAD

**Issue by veyalla** [NVIDIA/gpu-operator#10]
https://devblogs.nvidia.com/nvidia-gpu-operator-simplifying-gpu-management-in-kubernetes/ seems to suggest this should work on the Jetson Nano. However, I could not get it to work. 

I used the latest SD card image for Nano which did not have `ipmi_msghandler`. I tried to helm install the operator anyway and `nfd-worker` pod failed because it pulled an x64 image...

**Comment by RenaudWasTaken** [comment]
Hello!

This doesn't currently work on a Jetson Nano :)

**Comment by veyalla** [comment]
@RenaudWasTaken 

Thank you for clarifying. Is Nano support on your roadmap, any timelines you can share?

**Comment by David-VTUK** [comment]
As @veyalla has previously highlighted, https://developer.nvidia.com/blog/nvidia-gpu-operator-simplifying-gpu-management-in-kubernetes/ implies this is supported, but in this GH issue it's stated otherwise.

@RenaudWasTaken Is there a roadmap to add support? Is it being actively worked on? If not, can the original post be modified as it's contradictory.
