### ISSUE TITLE
Operator installmode AllNamespaces 

### ISSUE THREAD

**Issue by geoberle** [NVIDIA/gpu-operator#109]
Context: Operator 1.3.1 running on Openshift 4.6

I was wondering why the GPU operator must be installed in the openshift-operators namespace. By that it is visible in all Openshift namespaces since the OperatorGroup in openshift-operators does not restrict visiability. Also all users in all namespaces get access to the ClusterPolicy CRD. In the end it is most likely not an issue because the operator itself will not listen to those instances of the CRD, but it still introduces some noise in the available operators list of a namespace.

Is there a way to install the operator in another namespace where i have more control over the operatorgroup? openshift-operators has this special role within Openshift and therefore i don't want to modify anything there.

**Comment by shivamerla** [comment]
@geoberle since gpu-operator deploys all resources in "gpu-operator-resources" project irrespective of where operator is installed, we had to support only Multi-Namespace and All-Namespaces Or else monitoring wouldn't work. We are planning to avoid extra namespace "gpu-operator-resources" in coming releases and deploy everything in same namespace as operator.

**Comment by geoberle** [comment]
Thank you for the explanation. Looking forward to that release!

**Comment by shivamerla** [comment]
This has been fixed, starting with `v1.9.0` operator is installed in dedicated namespace `nvidia-gpu-operator`(default)
