### ISSUE TITLE
New MIG slicing not visible outside of Pod

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#117]
While working on the MIG slicing for the GPU operator, I observed that if I launch a Pod and reconfigure the MIG slicing:

```
      nvidia-smi mig -dci 
      nvidia-smi mig -dgi
      nvidia-smi mig -cgi "$DRV_MIG_MODE" -cgi 1 -C
      nvidia-smi -L
```

the new slicing is correctly reported by `nvidia-smi -L` inside this Pod, but the other Pods do not see it.

A workaround to propagate the MIG slicing is to call `nvidia-smi -L` inside the `driver-daemonset` local Pod. This will have the side effect to propagate the MIG reconfiguration and make it visible to all the existing and new Pods.

**Comment by klueska** [comment]
This feels like the same underlying cause might be triggering:
https://github.com/NVIDIA/gpu-monitoring-tools/issues/142

**Comment by klueska** [comment]
One thing to try to confirm my suspicion is to:
1) Run the container as --privileged
2) Set up a hostPath mount for /dev over /dev inside the container

That way, any `/dev` nodes created inside the container while reconfiguring MIG will always be reflected back on the host.

**Comment by klueska** [comment]
My assumption is that after doing this, you won't need the `nvidia-smi -L` calls inside any other containers.

**Comment by kpouget** [comment]
@klueska I tried this and it surely works better with it than without it, but I still see errors in the Pod creation.

In fact this morning, I had to manually call `nvidia-smi -L` in the driver to pass the `nvidia-driver-validation` validation.

This was a full/fresh deployment of the driver. Earlier this week the `/dev` solution appeared to work well, but I wasn't redeploying the driver ...

**Comment by klueska** [comment]
`/dev` would need to be mounted into the `driver` container as well.
(And again, this is just to confirm my suspicions, not a proposed solution).

That way, any device nodes it creates will be reflected on the host `/dev` and then when that is mounted in everyone elses container they see the changes too.

**Comment by kpouget** [comment]
> `/dev` would need to be mounted into the `driver` container as well.

this was missing in my setup, I'll add it and I'll see if the problem happens again, thanks for the update

> (And again, this is just to confirm my suspicions, not a proposed solution).
ok, that wasn't fully clear to me.

I wonder if mounting `/dev` on a Pod (already privileged) changes anything regarding security...

**Comment by klueska** [comment]
Having `--privileged` means it has the ability to `mrw` on the cgroups for *all* devices.
But if it actually does create a device node, that will only be reflected in its own `/dev` mount.
By mounting in the host `/dev` the device nodes created will be reflected back on the host for all to see.
Again -- not a permanent solution.

**Comment by kpouget** [comment]
> Having --privileged means it has the ability to mrw on the cgroups for all devices.

yes, what I meant is that the GPU-operator `driver`Pod already runs with high privileges, see there:
https://github.com/NVIDIA/gpu-operator/blob/38e7930/assets/state-driver/0500_daemonset.yaml#L40
```
      hostPID: true
      hostNetwork: true
      securityContext:
          privileged: true
          seLinuxOptions:
            level: "s0"
```
so I wonder if mounting `/dev` gives new privileges, or if the security level remains identical.

**Comment by klueska** [comment]
I think I may have gotten to the bottom of this issue.

When `libnvidia-container` starts up, one of the first things does is load the `nvidia` kernel module (if not already loaded) as well as create the `/dev/nvidiactl`, `/dev/nvidia-uvm`, `/dev/nvidia-modeset`, and `/dev/nvidia*` device nodes on the host file system (so that it can simply mount them in later as necessary).

https://github.com/NVIDIA/libnvidia-container/blob/master/src/nvc.c#L192..L218

Later on it selectively bind-mounts these devices into the container as necessary (depending on which devices should be injected as well as what capabilities are set):

https://github.com/NVIDIA/libnvidia-container/blob/master/src/nvc_mount.c#L616..L619

When adding MIG support, I added the code to bind-mount any necessary `nvidia-capabilities` from `/dev/nvidia-caps` into a container to give it access to a MIG device (or enable it to configure / monitor a set of MIG devices depending on the capability):

https://github.com/NVIDIA/libnvidia-container/blob/master/src/nvc_mount.c#L655..L658

However, I didn't add the logic to pre-create these device nodes on the host at startup time. Which means that if they donÄt already exist -- the `libnvidia-container` will fail to bind-mount them and throw an error.

So regarding....

> A workaround to propagate the MIG slicing is to call nvidia-smi -L inside the driver-daemonset local Pod. This will have the side effect to propagate the MIG reconfiguration and make it visible to all the existing and new Pods

By running `nvidia-smi` in the driver container, you are triggering the creation of these device nodes on the host, so they are available the next time `libnvidia-container` attempts to bind-mount them.

This obviously answers why this would fix things for new pods, but it is still a mystery to me why it would suddenly make them visible to existing pods (unless they have the driver's `/dev` folder (i.e. `/run/nvidia/driver/dev`  mounted in over their `/dev` folder).

In any case, I will look into adding the proper fix into `libnvidia-container` to pre-create these nodes before the bind mount.

Thanks again for reporting this important issue.

**Comment by klueska** [comment]
A PR is open for this now, please take a look:
https://gitlab.com/nvidia/container-toolkit/libnvidia-container/-/merge_requests/53

I will push an RC with this change sometime in the next few days.

**Comment by klueska** [comment]
The RC is live:
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.3.3-rc.1

Make sure you enable the `experimental` apt/yum repos for your distro if you want to try it out (as described here):
https://nvidia.github.io/libnvidia-container/

**Comment by kpouget** [comment]
thanks for the update @klueska, I've been able to deploy the image in my cluster, and from what I can see, it works as expected!

I removed the periodic `nvidia-smi -L` from my `driver-container`, and MIG slicing updates are correctly exposed to the different Pods.

I'll keep using this RC image until the final one is published, so I'll update the ticket if I notice anything turning wild.

**Comment by klueska** [comment]
Just to make sure, are you using rc.1 or rc.2 (I pushed a new patch for rc.2 late last night because I was pretty sure rc.1 wouldn't work).

**Comment by kpouget** [comment]
It's these 2 packages that I updated in the custom image I built:
```
(1/2): libnvidia-container-tools-1.3.3-0.1.rc.2 586 kB/s |  43 kB     00:00
(2/2): libnvidia-container1-1.3.3-0.1.rc.2.x86_ 886 kB/s |  87 kB     00:00
```

**Comment by shivamerla** [comment]
Closing this with complete MIG manager support with version `v1.7.0`
