### ISSUE TITLE
GPU operator bundle 1.4.0 in Redhat Operator Catalog

### ISSUE THREAD

**Issue by geoberle** [NVIDIA/gpu-operator#128]
I was looking for the version 1.4.0 of the GPU operator bundle for Openshift but was not able to find it anywhere.
catalog.redhat.com is listing only version 1.3.1

Thanks you
Gerd

**Comment by shivamerla** [comment]
@geoberle its still in the process of validation with RedHat before we post the bundle to RH catalog. There was a delay on this due to holidays. We are targeting this by end of next week.

**Comment by shivamerla** [comment]
1.4.0 version is published to RH catalog now

**Comment by geoberle** [comment]
Thank you for letting me know. I will give the new version and MIG a try !

**Comment by klueska** [comment]
MIG will likely not work with the operator because the MIG support in the device plugin and GFD for assume that MIG has been preconfigured on your GPUs before these components come on line. Since the operator itself is in charge of installing the driver on the node, there is no opportunity to set up this MIG configuration between the driver being installed and the plugin coming online. We plan to have a way to deal with this cleanly in future releases, but it probably won't work as one might expect in 1.4.0.
