### ISSUE TITLE
driver sign on secure boot enabled node

### ISSUE THREAD

**Issue by mumblez** [NVIDIA/gpu-operator#141]
Hi,

Just wondering someone can help advise on how best to sign the driver for a secure boot enabled node.

Do I need to somehow exec into the container with MOK keys mounted to sign after it starts?
Is there a clean way to set this up without forking and modifying the driver image? (nvcr.io/nvidia/driver)

Many Thanks

**Comment by nvjmayo** [comment]
It's not supported at this time. Building Driver Container from Docker by hand would be the easiest to hack together. You would need to edit the distro-specific script (e.g. `ubuntu20.04/nvidia-driver`) to apply the arguments and paths for the public and private keys, and bind mount the public and private keys.
A more production-ready solution would need access to public/private keys whenever GPU operator starts the Driver Container, because it can at any time trigger a driver build. I don't like the idea of letting an automated system hold onto driver signing keys. I would prefer from a security stand point not to implement this and have it remain a manual process initiated by a cluster administrator.

**Comment by mumblez** [comment]
@nvjmayo thanks for the info, maybe there's a possibility to have a prebuilt and signed kernel modules that Nvidia maybe sign with specific keys and include the public part of the key in the image (or anywhere), then admins could enrol the public cert ahead of time (MOK or db key), though I guess this would create a big matrix of modules to maintain per kernel version.

I understand it's not straight forward.

**Comment by shivamerla** [comment]
@mumblez we recently added support for installing Canonical signed drivers on Ubuntu 20.04: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/appendix.html#installing-precompiled-and-canonical-signed-drivers-on-ubuntu20-04

Closing this issue, please re-open if you face issues installing these modules.
