### ISSUE TITLE
Running 2 replicas of gpu-operator for HA

### ISSUE THREAD

**Issue by povils** [NVIDIA/gpu-operator#150]
Hey!
Is there a reason why we can't run at least 2 gpu-operators to achieve a better HA?
https://github.com/NVIDIA/gpu-operator/blob/master/deploy/operator.yaml#L1

**Comment by shivamerla** [comment]
@povils theoretically yes since we have leader election enabled. But do you have a strong use case which requires this? Currently when node goes unreachable, it takes about 5-8 minutes for the pod to be re-scheduled, but once initial deployment is done and all components are running in `gpu-operator-resources` namespace, operator mostly stays idle anyway.

**Comment by povils** [comment]
@shivamerla thanks for answering!
Hmm.. But don't we require gpu-operator to be running when new gpu nodes join a cluster?
In our case we use cluster autoscaling so we can have 0 or 100 gpu nodes depending on sheduling requests

**Comment by shivamerla** [comment]
@povils gpu-operator doesn't need to run on all nodes, hence its created as a Deployment. All the required components on GPU nodes are deployed as Daemonsets by gpu-operator, so they automatically get created on new nodes. GPU operator ensures that all required Daemonsets are created and running in `gpu-operator-resources` namespace.

**Comment by povils** [comment]
@shivamerla Ok that explains it! thank you :)

**Comment by yyardeng** [comment]
hey, i would like to get clarification on this again - would it not still make sense to desire the GPU operator to be highly available, so that it can keep ensuring the daemonsets are running as required, even if one of the operator replicas is down for some reason?

> theoretically yes since we have leader election enabled
is this still true for more recent releases?
