### ISSUE TITLE
Airgap Install Help

### ISSUE THREAD

**Issue by gwisaacs2** [NVIDIA/gpu-operator#191]
Hello,

Sorry I did not use your issue template because I have some questions with the installation. My situation is a little unique. I’m training AI on an isolated LAN running k3s 1.17. Because we’re using an offline network, we completely air gapped the entire k3s rancher install — not even using helm. We have an NVIDIA DGX running Ubuntu 18.04 with CUDA 11.2 and nvidia-container-toolkit (instead of nvidia-docker2). Our other nodes are basically in charge of running our environment, and those are running rhel 7.8, CUDA 10.2, and container-toolkit as well.

We’re not having an issues getting the containers to access the GPU, but the functionality we’re trying to achieve is adding the GPU limit. If an AI workload is scheduled on GPU-0 of the DGX, we want other workloads that are scheduled to go to a different GPU instead of GPU-0 that’s occupied.

I tried creating a Daemonset of just the k8s-device-plugin, but it was looking for our “manifests” directory, which I think is created by kubelet or kubeadm (?), which we don’t have.

I’ve been following the instructions on your site [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html).

My questions are: can I just create a Daemonset of all of the containers that gpu-operator requires?

If so, since the DGX is running a different OS, driver version, and cuda version, would I need two Daemonsets or can i just disregard the version verification containers?

Will I need to remove nvidia-container-toolkit and replace with nvidia-docker2?

We have multiple AI agents training on 300+ containers, so ruining our k3s cluster would be a huge burden. Let me know what you guys think! Thanks in advance. We could really use the help

**Comment by shivamerla** [comment]
@gwisaacs2 sorry for the delay, You could still use GPU Operator with air-gapped installs. We are releasing 1.7.0 of operator which lets you by-pass `driver` and `container-toolkit` installation. Since you already have them configured on your node, you can use this option to deploy operator. If you manually download all images required for `1.7.0` release(Refer to all images required here: https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/values.yaml), then operator will use them with default  imagePullPolicy set to `IfNotPresent`.

Regarding device-plugin issue on k3s, can you copy the error you are seeing and deployment spec you used? It only uses `/var/lib/kubelet/device-plugins` for socket files.
