### ISSUE TITLE
WITH_REBOOT variable - not clear how to set it

### ISSUE THREAD

**Issue by FlorinAndrei** [NVIDIA/gpu-operator#243]
This is a documentation issue, but a quick reply here could help a lot.

Reading this page...

https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/gpu-operator-mig.html

...I've found this quote:

> In a CSP IaaS environment such as Google Cloud, ensure that the mig-manager variable WITH_REBOOT is set to “true”. Refer to the note in the MIG User Guide for more information on the constraints with enabling MIG mode.

There is no mention anywhere else in the document about that variable. The linked page makes no mention of it either. A google search has not revealed anything mentioning that variable.

So, how to set that variable? Is it enough to declare it as an environment variable before running `helm install gpu-operator`?

Thanks!

**Comment by cdesiniotis** [comment]
Thanks for raising this. Our docs definitely need to be improved.

The WITH_REBOOT env variable is set here in `values.yaml`. Its an environment variable for the migManager pod.
https://github.com/NVIDIA/gpu-operator/blob/832f3175889625005e711c7c49d314e100d52892/deployments/gpu-operator/values.yaml#L215

To set the value of this variable, you can either directly download and modify `values.yaml` prior to running `helm install -f values.yaml gpu-operator`. The -f flag will use your modified `values.yaml` file instead of our default.

Or you can set that variable via the command line (not sure if there is a better/more concise way of doing this with --set):

`helm install gpu-operator --set migManager.env[0].name=WITH_REBOOT --set migManager.env[0].value=true`

**Comment by FlorinAndrei** [comment]
I'm trying to use the command line, but I get this error:

```
Error: ClusterPolicy.nvidia.com "cluster-policy" is invalid: spec.migManager.env.value: Invalid value: "boolean": spec.migManager.env.value in body must be of type string: "boolean"
```

I've tried quoting the value string, escaping the square brackets with backslash, but nothing helps.

**Comment by cdesiniotis** [comment]
Try using --set-string instead:

`helm install gpu-operator --set migManager.env[0].name=WITH_REBOOT --set-string migManager.env[0].value=true`

**Comment by FlorinAndrei** [comment]
That worked, thanks!
