### ISSUE TITLE
Support for tainted nodes

### ISSUE THREAD

**Issue by silashansen** [NVIDIA/gpu-operator#26]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe specialresources --all-namespaces`)

### 1. Issue or feature description
Our GPU nodes are tainted with dedicated=gpu:NoSchedule. This means that the gpu-operator-resource pods/daemonsets are not able to run on those nodes, unless we manually edit the definitions after the operator has created them, which is not a viable solution.

We'd love to see a way to provide tolerations in the values provided to the helm chart.

### 2. Steps to reproduce the issue
Create node with taints and run the operator

**Comment by gs11** [comment]
I second this request, but any suggested workarounds are welcome.

**Comment by BarthV** [comment]
:+1: this is critically needed.
I'm going to see if I'm able to submit something about this

**Comment by BarthV** [comment]
At the current state it seems not that simple to customize operator's deployments.
In my case :
* nvidia-container-toolkit-daemonset is deployed from a static asset file https://github.com/NVIDIA/gpu-operator/blob/master/assets/state-container-toolkit/0400_container_toolkit.yml
* This file is parsed by the operator and added to the resources managed by the controller (in a clusterPolicyController object).
* This object is modified by preprocess functions (preProcessDaemonSet) that overrides image and tag from ENV vars (inside getToolkit func)
* This ENV var is loaded from a ConfigMap in some Helm templates (operator-configmap.yaml). It holds only the processed image path of the toolkit docker image.

This is a bit unusual (and complex) behavior for k8s operators.
So in the current state of this project, I think the best way would be to add an additional ENV var with a custom yaml and then deep merge this yaml in the specs inside the existing preProcessDaemonSet function ...

But it's rather rewrite everything and directly manipulate kube objects in code instead of seeing static assets in repo blindly parsed like this :'(

**Comment by RenaudWasTaken** [comment]
> This is a bit unusual (and complex) behavior for k8s operators.

It is complex, the reason for this design is that we intend to manage the different components on a per node basis. As opposed to the current strategy, cluster-wide (through daemon-set).

This is mainly to ensure correct validation of the different components and being able to handle incorrect state (e.g: Driver crash, ...), upgrades of the driver and upgrades of the node's kernel.

Unfortunately that means that passing down information to the static assets is pretty convoluted. I was thinking of building a config map to do so.

**Comment by BarthV** [comment]
understood.

For sure I'd be glad to see these assets as configMaps ! I would add way more flexibility to this tool.

**Comment by shivamerla** [comment]
@BarthV @silashansen Tolerations are configurable for all GPU Operator components via Helm values.yaml. Default toleration added to all components is 

```
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
```
