### ISSUE TITLE
The DriverToolkit is enabled in the GPU Operator ClusterPolicy, but the NFD version deployed in the cluster is too old to support it.

### ISSUE THREAD

**Issue by arpitsharma-hexad** [NVIDIA/gpu-operator#324]
Hello Team,

We are getting errors as "The DriverToolkit is enabled in the GPU Operator
ClusterPolicy, but the NFD version deployed in the cluster
is too old to support it."

This error only appears when there are no GPU nodes and this alert keeps on firing. You can reproduce it easily on your side. Can you help here?

NFD version- 4.9.0-202201210133
OpenShift version - 4.9.18

Many Thanks

**Comment by kpouget** [comment]
indeed, it seems that the alert will fire incorrectly if there is no GPU node:
```
if hasCompatibleNFD {
	n.operatorMetrics.openshiftDriverToolkitNfdTooOld.Set(0)
} else {
	n.operatorMetrics.openshiftDriverToolkitNfdTooOld.Set(1)
}
```
```
hasCompatibleNFD := len(n.ocpDriverToolkit.rhcosVersions) != 0
```
```
if hasCommonGPULabel(labels) {
     ...
	f n.ocpDriverToolkit.requested {
	rhcosVersion, ok := labels[nfdOSTreeVersionLabelKey]
	if ok {
		n.ocpDriverToolkit.rhcosVersions[rhcosVersion] = true
```
the issue is that the `n.ocpDriverToolkit.rhcosVersions` map is only populated when `hasCommonGPULabel()`, so without GPU node, the map remains empty

---

I guess the fix should be to check `labels[nfdOSTreeVersionLabelKey]` outside of the `hasCommonGPULabel` test, and set a new flag `n.ocpDriverToolkit.hasCompatibleNFD` if the key is found

**Comment by fabiendupont** [comment]
@arpitsharma-hexad, this should be solved by https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/405 and be shipped in a further release.

**Comment by arpitsharma-hexad** [comment]
Many thanks team
