### ISSUE TITLE
[Feature Request] console-plugin-nvidia-gpu / GPU Operator Dashboard per project

### ISSUE THREAD

**Issue by Alwinator** [NVIDIA/gpu-operator#462]
It would be very useful if the [GPU Operator dashboard plugin](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/openshift/enable-gpu-op-dashboard.html), could also show the metrics shown in the overview page, but for a single project. This would allow our customers (who only have access to certain projects), to see the GPU utilization for their projects.

**Comment by simonkrenger** [comment]
@Alwinator Have you reviewed the following issue on the [rh-ecosystem-edge/console-plugin-nvidia-gpu](https://github.com/rh-ecosystem-edge/console-plugin-nvidia-gpu) repository: https://github.com/rh-ecosystem-edge/console-plugin-nvidia-gpu/issues/50

This may have some additional information of what is possible and what is not possible. In general I would recommend to open the issue in that project instead of here (as it concerns the "console-plugin-nvidia-gpu"). Hope that helps

**Comment by Alwinator** [comment]
Issue moved to https://github.com/rh-ecosystem-edge/console-plugin-nvidia-gpu/issues/57

@simonkrenger Thanks for the feedback, however, it would still be great if the customers could see their own GPU utilization for their projects or their pods.
