### ISSUE TITLE
Deprecated API used

### ISSUE THREAD

**Issue by tormig-softronic** [NVIDIA/gpu-operator#490]
### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [X] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
After an upgrade to Openshift 4.11 the following warning appeared: 
"Deprecated API that will be removed in the next version is being used. Removing the workload that is using the policy.v1beta1/podsecuritypolicies API might be necessary for a successful upgrade to the next cluster version. Refer to `oc get apirequestcounts podsecuritypolicies.v1beta1.policy -o yaml` to identify the workload.

It turns out that one of the culprits is the GPU Operator:
VERBS       USERNAME                                                                               USERAGENT
delete         system:serviceaccount:nvidia-gpu-operator:gpu-operator          gpu-operator/v0.0.0

The version of the operator is v22.9.2

Is this the same problem as mentioned in #484 and #451?

**Comment by shivamerla** [comment]
@tormig-softronic Yes, this is the related issue. In your case OCP version is 4.11 and you can ignore the warning and continue to use the GPU Operator. It will not deploy any PSP resources for OCP, but is retained for other orchestrators like VMware Tanzu. This is causing failures in OCP 4.12 pre-release versions due to semVer comparison issue where any cleanup attempts will fail. That will be fixed in an upcoming release in March.

**Comment by arpitsharma-hexad** [comment]
Hi @shivamerla Do you know when the new release will be there containing that fix? We are planning to upgrade to 4.12.
Thanks

**Comment by tormig-softronic** [comment]
Hello, please note that Openshift 4.11 will enter "Maintenance support" april 17 and this issue is effectively stopping an upgrade to the fully supported version i.e. 4.12.

**Comment by shivamerla** [comment]
@arpitsharma-hexad @tormig-softronic the current certified bundle `v22.9.2` is supported on OCP 4.12. We will not attempt to create or delete any PSP resources for OCP 4.12 (based on k8s 1.25). Only with OKD 4.12 we had an issue since the k8s version was `v1.25.0-2653+a34b9e9499e6c3-dirty` which we had a bug in the semVer check. This was not the case with OCP 4.12. You can ignore the warning that appears on 4.11.

**Comment by shivamerla** [comment]
This has been resolved with v23.3.0.
