### ISSUE TITLE
OpenShift 4.4.3, installed Nvidia gpu operator from hub in gpu-operator-resources, missing package

### ISSUE THREAD

**Issue by rspierz** [NVIDIA/gpu-operator#61]
Stuck in crashloop for all nvidia-driver-daemonset pods:

+ set -eu
+ RUN_DIR=/run/nvidia
+ PID_FILE=/run/nvidia/nvidia-driver.pid
+ DRIVER_VERSION=440.64.00
+ KERNEL_UPDATE_HOOK=/run/kernel/postinst.d/update-nvidia-driver
+ '[' 1 -eq 0 ']'
+ command=init
+ shift
+ case "${command}" in
++ getopt -l accept-license -o a --
+ options=' --'
+ '[' 0 -ne 0 ']'
+ eval set -- ' --'
++ set -- --
+ ACCEPT_LICENSE=
++ uname -r
+ KERNEL_VERSION=4.18.0-147.8.1.el8_1.x86_64
+ PRIVATE_KEY=
+ PACKAGE_TAG=
+ for opt in ${options}
+ case "$opt" in
+ shift
+ break
+ '[' 0 -ne 0 ']'
+ init
+ echo -e '\n========== NVIDIA Software Installer ==========\n'

========== NVIDIA Software Installer ==========

+ echo -e 'Starting installation of NVIDIA driver version 440.64.00 for Linux kernel version 4.18.0-147.8.1.el8_1.x86_64\n'
Starting installation of NVIDIA driver version 440.64.00 for Linux kernel version 4.18.0-147.8.1.el8_1.x86_64

+ exec
+ flock -n 3
+ echo 1499229
+ trap 'echo '\''Caught signal'\''; exit 1' HUP INT QUIT PIPE TERM
+ trap _shutdown EXIT
+ _unload_driver
+ rmmod_args=()
+ local rmmod_args
+ local nvidia_deps=0
+ local nvidia_refs=0
+ local nvidia_uvm_refs=0
+ local nvidia_modeset_refs=0
+ echo 'Stopping NVIDIA persistence daemon...'
Stopping NVIDIA persistence daemon...
+ '[' -f /var/run/nvidia-persistenced/nvidia-persistenced.pid ']'
Unloading NVIDIA driver kernel modules...
+ echo 'Unloading NVIDIA driver kernel modules...'
+ '[' -f /sys/module/nvidia_modeset/refcnt ']'
+ '[' -f /sys/module/nvidia_uvm/refcnt ']'
+ '[' -f /sys/module/nvidia/refcnt ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ return 0
+ _unmount_rootfs
+ echo 'Unmounting NVIDIA driver rootfs...'
Unmounting NVIDIA driver rootfs...
+ findmnt -r -o TARGET
+ grep /run/nvidia/driver
+ _kernel_requires_package
+ local proc_mount_arg=
+ echo 'Checking NVIDIA driver packages...'
Checking NVIDIA driver packages...
+ [[ ! -d /usr/src/nvidia-440.64.00/kernel ]]
+ cd /usr/src/nvidia-440.64.00/kernel
+ proc_mount_arg='--proc-mount-point /lib/modules/4.18.0-147.8.1.el8_1.x86_64/proc'
++ ls -d -1 'precompiled/**'
+ return 0
+ _update_package_cache
+ '[' '' '!=' builtin ']'
+ echo 'Updating the package cache...'
Updating the package cache...
+ yum -q makecache
+ _install_prerequisites
++ mktemp -d
+ local tmp_dir=/tmp/tmp.K4LKmXpuN4
+ trap 'rm -rf /tmp/tmp.K4LKmXpuN4' EXIT
+ cd /tmp/tmp.K4LKmXpuN4
+ dnf install -q -y elfutils-libelf.x86_64 elfutils-libelf-devel.x86_64
**Error: Unable to find a match: elfutils-libelf-devel.x86_64**
++ rm -rf /tmp/tmp.K4LKmXpuN4
+ _shutdown
+ _unload_driver
+ rmmod_args=()
+ local rmmod_args
+ local nvidia_deps=0
+ local nvidia_refs=0
+ local nvidia_uvm_refs=0
+ local nvidia_modeset_refs=0
+ echo 'Stopping NVIDIA persistence daemon...'
Stopping NVIDIA persistence daemon...
+ '[' -f /var/run/nvidia-persistenced/nvidia-persistenced.pid ']'
Unloading NVIDIA driver kernel modules...
+ echo 'Unloading NVIDIA driver kernel modules...'
+ '[' -f /sys/module/nvidia_modeset/refcnt ']'
+ '[' -f /sys/module/nvidia_uvm/refcnt ']'
+ '[' -f /sys/module/nvidia/refcnt ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ return 0
+ _unmount_rootfs
+ echo 'Unmounting NVIDIA driver rootfs...'
Unmounting NVIDIA driver rootfs...
+ findmnt -r -o TARGET
+ grep /run/nvidia/driver
+ rm -f /run/nvidia/nvidia-driver.pid /run/kernel/postinst.d/update-nvidia-driver
+ return 0

**Comment by rspierz** [comment]
Specifically this package is missing from ubi image: **elfutils-libelf-devel**

**Comment by rspierz** [comment]
This continues to be an issue on the latest image: "nvidia/driver:440.64.00-rhcos4.4" pushed within 24hrs.

Please let me know if theres a workaround or another image I can test, using openshift 4.4.4

**Comment by rbo** [comment]
I run into the same issue with `nvidia/driver:440.64.00-rhcos4.4`. The problem is you have to entitle your OpenShift 4 cluster.  As mention in [BZ 1835446](https://bugzilla.redhat.com/show_bug.cgi?id=1835446)

Follow the [NVIDIA documentation](https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html#openshift-gpu-install-gpu-operator-via-helmv3) "Add a cluster-wide entitlement via a Kubernetes secret." to entitle your cluster

**Comment by dualvtable** [comment]
That's correct. Please see this info:

This error indicates that the UBI-based driver pod does not have subscription entitlements correctly mounted so that additional required UBI packages are not found. Please refer to this (https://www.openshift.com/blog/how-to-use-entitled-image-builds-to-build-drivercontainers-with-ubi-on-openshift) [blog post] (on the details for entitling your cluster for the driver pod on non-RHEL hosts. You will need a valid subscription that is attached to a Red Hat system, even a Virtual subscription. Please refer to your account details at https://access.redhat.com/management/
