### ISSUE TITLE
Use ISO 8601 format for datetime stamps in logs

### ISSUE THREAD

**Issue by linkvt** [NVIDIA/gpu-operator#66]
Not a bug but an improvement:
Please switch to logging with the standardized ISO 8601 date time stamp which is human and machine readable in opposite to the current painful unix timestamps used in the logs.

I understand that a central logging system would help but find it really hard to quickly check the logs and pinpoint the time when the issue happened, with lines as the following:
```
{"level":"info","ts":1591777763.3031344,"logger":"controller_clusterpolicy","msg":"ClusterPolicy","ResourceStatus":"NotReady"}
``` 
instead of something like:
```
{"level":"info","ts":2020-06-01T18:43:26.000Z,"logger":"controller_clusterpolicy","msg":"ClusterPolicy","ResourceStatus":"NotReady"}
```

There seems to be an easy way how this could be done in a kubernetes operator, see https://github.com/elastic/cloud-on-k8s/issues/1587

Thanks

**Comment by nvjmayo** [comment]
thanks for the suggestion, the some equivalent to the relevant code in https://github.com/elastic/cloud-on-k8s/pull/1699 would need to be done in order for this to happen.

**Comment by creydr** [comment]
@linkvt: since version 1.2 you can specify the time format via helm. E.g. in your [`values.yaml`](https://github.com/NVIDIA/gpu-operator/blob/565ea353fec1a434a59a3e1eceae21dd3dd2cacb/deployments/gpu-operator/values.yaml#L43):

```yaml
  logging:
    timeEncoding: iso8601
```

possible values are:
* `epoch` (which is the standard)
* `millis`
* `nano`
* `iso8601`

or patch the yaml directly (e.g. in case you use kustomize) and set the required [argument of the operator](https://github.com/NVIDIA/gpu-operator/blob/565ea353fec1a434a59a3e1eceae21dd3dd2cacb/deployments/gpu-operator/templates/operator.yaml#L39):
```
args:
- "--zap-time-encoding=iso8601"
```
