### ISSUE TITLE
NVIDIA driver installed by GPU operator fails on reboot

### ISSUE THREAD

**Issue by TheMosquito** [NVIDIA/gpu-operator#70]
We are trying to use the NVIDIA GPU operator to install NVIDIA driver/compiler/libs/runtime etc. on open-source kubernetes and we are running into a problem. This problem is very easy to reproduce.
 
Hardware: 96 core Xeon, 200GB RAM
OS/Distro: Linux  4.15.0, ubuntu 18.04.03
Docker 19.03.12

Steps to reproduce:
- Fresh install of the 18.04.03
- Used the GPU operator ansible playbook
- everything comes up beautifully (so nice! thanks for this great way to install)
- verified the driver/libs/runtime are working by running a container that uses the CUDA libraries to exercise the GPU

At that point all is good.

Then we rebooted.

After reboot the NVIDIA driver container goes into a crash/backoff loop. It seems to be trying to reinstall the driver, but since it is already there it is failing.

Anurag Guda helped us on this so he knows some more details.

**Comment by angudadevops** [comment]
Used [EGX DIY Stack](https://github.com/NVIDIA/egx-platform) with GPU Operator, once initial setup is done. When we rebooted the host, NVIDIA Driver container failed to run. 

In logs we can see Kernel driver is in use.

**Comment by TheMosquito** [comment]
A couple of weeks ago this was a problem, but in the last few days we have rebooted a couple of times and this issue did *not* show up. I guess it is a [HeisenBug](https://en.wikipedia.org/wiki/Heisenbug)

**Comment by mikehollinger** [comment]
I seem to be hitting this as well in an OpenShift 4.3.33 cluster, with GPU operator nvidia/gpu-operator:1.1.7

[nvidia-driver-daemonset-gqb2m-nvidia-driver-ctr.log](https://github.com/NVIDIA/gpu-operator/files/5144479/nvidia-driver-daemonset-gqb2m-nvidia-driver-ctr.log)

Should I be worried about this? It seems like I can deploy pods with GPUs, and things are working fine?

**Comment by shivamerla** [comment]
Fixed by: https://github.com/NVIDIA/gpu-operator/commit/c937c68a5f8469cdedea4c78fc8d681ad5d7c62c

The problem was when gpu-operator is installed, operator maintains ordering of pods{driver --> toolkit --> device-plugin --> DCGM exporter --> GFD), however on reboot, this ordering will not be maintained and toolkit container migth set runtime to `nvidia` before drivers could be loaded. After this driver container could never run. This is fixed now by adding initContainers to ensure drivers are loaded before runtime can be set.
