### ISSUE TITLE
unknown field "grpc" in io.k8s.api.core.v1.Probe

### ISSUE THREAD

**Issue by corrtia** [NVIDIA/gpu-operator#724]
### 1. Quick Debug Information
* OS/Version(e.g. RHEL8.6, Ubuntu22.04):Ubuntu20.04
* Kernel Version: v1.18.0
* Container Runtime Type/Version(e.g. Containerd, CRI-O, Docker): Docker v24.0.7
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS): K8s
* GPU Operator Version: v24.3.0

### 2. Issue or feature description
Error found while installing gpu-operator using helm:
```
helm install --wait --generate-name     -n gpu-operator --create-namespace     nvidia/gpu-operator
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe): unknown field "grpc" in io.k8s.api.core.v1.Probe, ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe): unknown field "grpc" in io.k8s.api.core.v1.Probe]
```

### 3. Steps to reproduce the issue
```
kubectl create ns gpu-operator
kubectl label --overwrite ns gpu-operator pod-security.kubernetes.io/enforce=privileged
kubectl get nodes -o json | jq '.items[].metadata.labels | keys | any(startswith("feature.node.kubernetes.io"))'
helm repo add nvidia https://helm.ngc.nvidia.com/nvidia
helm install --wait --generate-name     -n gpu-operator --create-namespace     nvidia/gpu-operator
```

**Comment by shivamerla** [comment]
@corrtia K8s version 1.18 is very old at this point and not supported by the operator.

**Comment by corrtia** [comment]
The k8s version is too low to cause it.Thanks!

**Comment by sycbbyes** [comment]
due to some legacy issue， we have to keep K8S with version: 1.22, while it cannot be applied via helm with error: 
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe): unknown field "grpc" in io.k8s.api.core.v1.Probe, ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe): unknown field "grpc" in io.k8s.api.core.v1.Probe]


how to get ride of this issue? is it possibel to install a former operator to get ride of this error?

thanks.

**Comment by namoshizun** [comment]
> due to some legacy issue， we have to keep K8S with version: 1.22, while it cannot be applied via helm with error: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe): unknown field "grpc" in io.k8s.api.core.v1.Probe, ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe): unknown field "grpc" in io.k8s.api.core.v1.Probe]
> 
> how to get ride of this issue? is it possibel to install a former operator to get ride of this error?
> 
> thanks.

Having the same issue while installing GPU operator on k8s 1.22 ...
