### ISSUE TITLE
Cluster autoscaler scaling to zero for GPU node pools

### ISSUE THREAD

**Issue by ranjb** [NVIDIA/gpu-operator#76]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [X] Are you running on an Ubuntu 18.04 node?
- [X] Are you running Kubernetes v1.13+?
- [X] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [X] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [X] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
In the context of the Kubernetes cluster autoscaler, it would appear that the GPU operator is not compatible with the  autoscaling to zero. This could be really useful on saving cost when operating expensive GPU instances

### 2. Steps to reproduce the issue
While the cluster autoscaler can successfully autoscale the GPU node pool to zero, it appears the operator executes periodic checks that are executed as running pods which end up triggering a scale-up event in the node pool which defeats the purpose of being able to scale to zero.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by silashansen** [comment]
Having native support for scaling to and from zero, would be very appreciated.

Since the gpu-operator is failing when there are no gpu-nodes (see details), **we don't see the periodic scale up that @ranjb describes.**

We're running cronjobs this way:
* A cronjob that requires gpu is triggered
* Clusterautoscaler provisions a gpu-instance
* The Job runs to completion
* Clusterautoscaler terminates the gpu-instance

This is **very cost efficient** and should therefore be supported.

### Details

When there is no gpu instance:
```
NAME                                                              READY   STATUS      RESTARTS   AGE
gpu-operator-657579678c-sfjl8                                     0/1     Error       13         13h
```
Output:
```
{"level":"info","ts":1609319235.8210428,"logger":"controller_clusterpolicy","msg":"Could not get any nodes to match nvidia.com/gpu.present label","Request.Namespace":"default","Request.Name":"Node","ERROR":""}
{"level":"info","ts":1609319235.8210719,"logger":"controller_clusterpolicy","msg":"Failed to apply transformation 'nvidia-driver-daemonset' with error: 'ERROR: Could not find kernel full version: ('', '')'"}
```

### Workaround:
**Warning: this is hacky and no large scale approach**
Schedule a "warmup" job that requires gpu 15 minutes before the *actual* cronjob to trigger the gpu-instance creation ahead of time.
This allows the cluster to stabilize and get everything in order, before the job is run.
The drawback here, is that it'll cost you 15 minutes of compute and you'll have the gpu-operator in an error-state whenever a job is not running (annoying to have failing pods around, I know).

Example:
```
> kubectl get cronjob

NAME                            SCHEDULE     SUSPEND   ACTIVE   LAST SCHEDULE   AGE
train-model-gpu-job-warmup      0 9 * * *    False     1        4m2s            37d
train-model-gpu-job           	15 9 * * *   False     0        19m             27d
```




You may need to experiment with the delay in your own cluster.

**Comment by shivamerla** [comment]
@ranjb From 1.5.0 version, GPU operator will continue to run with 0 GPU nodes. Please re-open if you still see this.
