### ISSUE TITLE
New GPU nodes do not get labeled with nvidia.com/gpu resources without restart of device-plugin pods

### ISSUE THREAD

**Issue by dagrayvid** [NVIDIA/gpu-operator#81]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [n] Are you running on an Ubuntu 18.04 node?
- [y] Are you running Kubernetes v1.13+?
- [y] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [?] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [y] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
Issue: when adding a new node to a cluster with the GPU operator running, they never get labelled as nvidia.com/gpu nodes. An easy work around is to delete the device plugin daemonset pods, however this makes scaling up GPU nodes hard to automate (for instance using the cluster autoscaler). I believe this is because of a race condition between the driver container and the device plugin.

### 2. Steps to reproduce the issue
- Install the GPU operator
- Add a GPU node to the cluster

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
The issue occurs even though all pods in the gpu-operator-resources namespace are in the running state

**Comment by geoberle** [comment]
We see this exact issue as well on openshift 4.4 and 4.5

**Comment by shivamerla** [comment]
@geoberle i will try to reproduce this locally.  There might be some delay in kubelet fetching device list after plugin registers with it once drivers are loaded on that node. Will update soon.

**Comment by shivamerla** [comment]
@geoberle i gave it a try with K8s 1.19 and didn't see this issue, device-plugin pods will be in crashloop on new node until driver pod installs all required Nvidia drivers on the node. As soon as device-plugin is running, i see kubelet updates the gpu resource info. OCP 4.4/4.5 maps to 1.17/1.18, will try with OCP or K8s 1.18 and update you next week.

**Comment by geoberle** [comment]
@shivamerla I will give this another try and will gather more information

**Comment by aychang95** [comment]
I have the same issue here. I'll sporadically get the a `Failed to initialize NVML: could not load NVML library.` error for the nvidia device plugin daemonset. After restarting/deletting the daemonset pod, like this issue and @geoberle mention above, everything seems fine and nvida.com/gpu resources are allocated.

@shivamerla 
It seems like all pre-requisite drivers and nvidia container runtimes are configured, so I agree the issue might come from the plugin daemonset not registering the the loaded nvidia componenets in time.

This issue came up with k8s.1.17.*

**Comment by aheifetz** [comment]
Using EKS (1.18) with the horizontal auto-scaler, I too add to restarting/deleting the daemonset pod after the auto-scaled servers came on-line

**Comment by kpouget** [comment]
> I believe this is because of a race condition between the driver container and the device plugin.


I think the issue comes from the usage of `DaemonSet` for deploying the GPU operator:

```
NAME                                 DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
gpu-feature-discovery                1         1         1       1            1           nvidia.com/gpu.present=true   15h
nvidia-container-toolkit-daemonset   1         1         1       1            1           nvidia.com/gpu.present=true   15h
nvidia-dcgm-exporter                 1         1         1       1            1           nvidia.com/gpu.present=true   15h
nvidia-device-plugin-daemonset       1         1         1       1            1           nvidia.com/gpu.present=true   15h
nvidia-driver-daemonset              1         1         1       1            1           nvidia.com/gpu.present=true   15h
```

when rebooting or adding a new node with `nvidia.com/gpu.present=true`, the DaemonSets will *all* (re)create Pods on the nodes, all at the same time, without any control of the GPU operator.

Eventually the Pod of the `nvidia-driver-daemonset` will load the `nvidia` driver. But _as far as I've seen_, the `nvidia-device-plugin-daemonset` Pod cannot detect the GPU when it restarts. It needs to be manually destroyed (and automatically recreated) to detect it.
