### ISSUE TITLE
Add Container Toolkit to NVIDIADriverSpec CRD

### ISSUE THREAD

**Issue by lengrongfu** [NVIDIA/gpu-operator#817]
Cause：https://github.com/NVIDIA/gpu-operator/issues/725

**Comment by cdesiniotis** [comment]
As the scope of the `NVIDIADriver` CRD is just the driver deployment, we are not planning to add additional components to it's spec. I am closing this issue as not planned. 

As mentioned in https://github.com/NVIDIA/gpu-operator/issues/725#issuecomment-2223976939 a better solution would be to leverage a distro-agnostic `container-toolkit` image so that multiple daemonsets are not required.
