### ISSUE TITLE
 nvidia-driver fails in air-gapped environment.

### ISSUE THREAD

**Issue by moonek** [NVIDIA/gpu-operator#91]
I installed gpu-operator in an environment where internet access is not available.

Most of the related pods are in CrashLookBackOff state,
```
# kubectl get po -n gpu-operator-resources
NAME                                             READY   STATUS             RESTARTS   AGE
gpu-operator-9ddd98f5c-fjkch                     0/1     CrashLoopBackOff   16         57m
node-feature-discovery-master-54c688cfc6-4wrw8   1/1     Running            0          90m
node-feature-discovery-worker-csp8j              1/1     Running            0          90m
node-feature-discovery-worker-xwd2x              1/1     Running            0          90m
nvidia-container-toolkit-daemonset-7dplz         1/1     Running            0          88m
nvidia-container-toolkit-daemonset-b5lmt         1/1     Running            0          88m
nvidia-driver-daemonset-9687x                    0/1     CrashLoopBackOff   15         56m
nvidia-driver-daemonset-vvhcv                    0/1     CrashLoopBackOff   15         56m
nvidia-driver-validation                         0/1     CrashLoopBackOff   22         88m
```

Only nvidia-driver outputs the following log.
```
# kubectl logs  nvidia-driver-daemonset-9687x -n gpu-operator-resources --previous

========== NVIDIA Software Installer ==========

Starting installation of NVIDIA driver version 450.80.02 for Linux kernel version 4.15.0-76-generic

Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Updating the package cache...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Resolving Linux kernel version...
Could not resolve Linux kernel version
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
```

The nvidia-driver image and environment information are as follows.
- nvcr.io/nvidia/driver:450.80.02-ubuntu18.04
- Ubuntu 18.04.4 LTS (4.15.0-76-generic)
- k8s v1.15.3
- docker-ce 19.03.5

Is nvidia-driver image not possible to operate in air-gapped environment?

**Comment by MrBoJo84** [comment]
The GPU Operator does not work in airgapped environments today but we are working towards air gapped support. We expect this feature to be available with the next release which is planned for Q42020.

**Comment by hongweijia** [comment]
Hi @shivamerla 
May I ask when will the fix be available ?
Most cases are air-gapped environment. So could you please prioritize this? Thanks!

BTW, is there any workaround?

**Comment by shivamerla** [comment]
@hongweijia we are planning to add air-gapped cluster support by early December. But all required changes are in place, so you can build private gpu-operator image and use helm install from source repo(instead of bundled chart repo). As you might know driver container need kernel-devel and kernel-headers packages to compile the driver, so you would need to make those available through local repository, example steps [mirror repo](https://help.ubuntu.com/community/Repositories/CommandLine.) Once local mirror is setup with required packages, then create configmap as below in `gpu-operator-resources` namespace

`kubectl create configmap repo-config -n gpu-operator-resources --from-file=/home/ubuntu/local-repo.list`

In the deployments/gpu-operator/values.yaml, specify above configmap as repoConfig under driver section:

```
driver:
  repoConfig:
    configMapName: repo-config
    destinationDir: /etc/apt/sources.list.d/
```

**Comment by hongweijia** [comment]
Hi @shivamerla 
Appreciate your help! Looking forward to the air-gapped installtion of GPU Operator in early December. Will try if need for the time-being.

**Comment by shivamerla** [comment]
@hongweijia 1.4.0 version of gpu-operator chart is published. Can you try it out with your system? You can repoConfig as my previous comment in values.yaml.

**Comment by hongweijia** [comment]
Hi @shivamerla
Thank you for the update!
Do you mean  1.4.0 version of gpu-operator officially supports the air-gapped installation?  Or it is still a workaround?
Thanks!

**Comment by shivamerla** [comment]
@hongweijia having a local mirror repository setup is a pre-requisite for air-gapped install of gpu-operator. Since drivers will be compiled for the running kernel, we need those packages to be pulled dynamically. The changes we made are to let users specify the configured mirror repository with configMap as indicated above.

**Comment by hongweijia** [comment]
Hi @shivamerla
Thank you for your detailed explanation!
BTW, may I ask do we have a step by step guide for the air-gap installation? Thanks!

**Comment by shivamerla** [comment]
@hongweijia requirements are highlighted here: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#considerations-to-install-in-air-gapped-clusters
